// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Convert(arg1) {
  return window['go']['main']['App']['Convert'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function GetAIConfig() {
  return window['go']['main']['App']['GetAIConfig']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function InspectSource(arg1) {
  return window['go']['main']['App']['InspectSource'](arg1);
}

export function InstallUpdate(arg1) {
  return window['go']['main']['App']['InstallUpdate'](arg1);
}

export function OpenLastOutputDir() {
  return window['go']['main']['App']['OpenLastOutputDir']();
}

export function PickCover() {
  return window['go']['main']['App']['PickCover']();
}

export function PickTXT() {
  return window['go']['main']['App']['PickTXT']();
}

export function SaveAIConfig(arg1) {
  return window['go']['main']['App']['SaveAIConfig'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function TestAIConnection(arg1) {
  return window['go']['main']['App']['TestAIConnection'](arg1);
}
