// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Convert(arg1:main.convertRequest):Promise<void>;

export function GetConfig():Promise<main.guiConfig>;

export function InspectSource(arg1:string):Promise<main.sourceInsight>;

export function OpenLastOutputDir():Promise<void>;

export function PickCover():Promise<string>;

export function PickTXT():Promise<string>;

export function SaveConfig(arg1:main.guiConfig):Promise<void>;
